-- 01y-postgrest.sql
-- PostgREST database setup: roles, API schema, permissions.
-- Runs after 01-schemas.sql (app schema exists) and before 02-partman.sql.
--
-- Architecture:
--   authenticator (LOGIN, NOINHERIT) — PostgREST connects as this role
--     ├── anon (NOLOGIN)            — unauthenticated requests
--     └── webuser (NOLOGIN)         — JWT-authenticated requests
--
--   api schema                      — exposed via PostgREST (views, functions)
--   app schema                      — internal tables (hidden from REST API)

\echo '=== Setting up PostgREST ==='

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------

-- Authenticator: PostgREST connects as this role, then switches via SET ROLE
CREATE ROLE authenticator LOGIN NOINHERIT PASSWORD 'authenticator';
\echo '  authenticator role created'

-- Anonymous: unauthenticated REST API access (read-only by default)
CREATE ROLE anon NOLOGIN;
GRANT anon TO authenticator;
\echo '  anon role created'

-- Webuser: JWT-authenticated REST API access (read-write)
CREATE ROLE webuser NOLOGIN;
GRANT webuser TO authenticator;
\echo '  webuser role created'

-- ---------------------------------------------------------------------------
-- API schema: everything here becomes a REST endpoint
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS api;
COMMENT ON SCHEMA api IS 'PostgREST API schema — exposed as REST endpoints. Put views and functions here, not raw tables.';

-- Grant schema usage to API roles
GRANT USAGE ON SCHEMA api TO anon, webuser;

-- Default privileges: auto-grant on future objects in api schema
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO webuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT EXECUTE ON FUNCTIONS TO anon, webuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT USAGE ON SEQUENCES TO webuser;

\echo '  api schema created with default privileges'

-- ---------------------------------------------------------------------------
-- Grant access to underlying schemas (for views that reference app tables)
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA app TO anon, webuser;
GRANT USAGE ON SCHEMA public TO anon, webuser;

-- anon can read app tables (through api views)
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT ON TABLES TO anon;
-- webuser can read/write app tables (through api views)
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO webuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT USAGE ON SEQUENCES TO webuser;

\echo '  app schema permissions granted to API roles'

-- ---------------------------------------------------------------------------
-- Helper: create a REST endpoint view from an app table
-- Usage: SELECT api_expose('app.users', 'users');
-- Creates: api.users view → SELECT * FROM app.users
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.api_expose(
    p_source_table TEXT,
    p_api_name TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_name TEXT;
BEGIN
    -- Default API name = table name without schema
    v_name := COALESCE(p_api_name, split_part(p_source_table, '.', 2));

    EXECUTE format(
        'CREATE OR REPLACE VIEW api.%I AS SELECT * FROM %s',
        v_name, p_source_table
    );

    -- Make view updatable (PostgREST uses INSTEAD OF triggers or simple views)
    EXECUTE format(
        'COMMENT ON VIEW api.%I IS %L',
        v_name,
        format('REST endpoint for %s. Auto-generated by api_expose().', p_source_table)
    );
END;
$$;

COMMENT ON FUNCTION public.api_expose IS
'Create a REST API view in the api schema from a source table.
The view is auto-updatable if it''s a simple SELECT * FROM single_table.
Usage: SELECT api_expose(''app.users'', ''users'');';

\echo '  api_expose() helper created'

-- ---------------------------------------------------------------------------
-- Helper: JWT claim accessor (use in RLS policies or functions)
-- Usage: SELECT current_user_id();  -- returns UUID from JWT sub claim
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS TEXT
LANGUAGE sql STABLE
AS $$
    SELECT coalesce(
        current_setting('request.jwt.claims', true)::json->>'sub',
        current_setting('request.jwt.claims', true)::json->>'user_id'
    );
$$;

COMMENT ON FUNCTION public.current_user_id IS
'Extract user ID from JWT claims (sub or user_id field). Use in RLS policies.';

\echo '  current_user_id() JWT helper created'

-- ---------------------------------------------------------------------------
-- Helper: get any JWT claim
-- Usage: SELECT jwt_claim('email');
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.jwt_claim(p_key TEXT)
RETURNS TEXT
LANGUAGE sql STABLE
AS $$
    SELECT current_setting('request.jwt.claims', true)::json->>p_key;
$$;

COMMENT ON FUNCTION public.jwt_claim IS
'Extract any claim from the current JWT token. Usage: SELECT jwt_claim(''email'');';

\echo '  jwt_claim() helper created'

-- ---------------------------------------------------------------------------
-- Update search_path to include api schema
-- ---------------------------------------------------------------------------
ALTER ROLE postgres SET search_path = public, api, app, analytics, embeddings, partman, ag_catalog;

\echo '  search_path updated with api schema'

\echo '=== PostgREST configured ==='
\echo ''
\echo 'Roles: authenticator (login), anon (read), webuser (read-write)'
\echo 'API schema: api (exposed via PostgREST on port 46433)'
\echo ''
\echo 'Quick start:'
\echo '  1. Create table:  CREATE TABLE app.todos (id serial, task text, done boolean);'
\echo '  2. Expose as API: SELECT api_expose(''app.todos'');'
\echo '  3. Query via REST: curl http://localhost:46433/todos'
\echo '  4. Insert via REST: curl -X POST http://localhost:46433/todos -d ''{"task":"hello","done":false}'''
